-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: backend/schema/abstractSchemaChanges/patch-flaggedrevs_tracking-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX frt_from_namespace_title;
DROP  INDEX frt_namespace_title_from;
CREATE TEMPORARY TABLE /*_*/__temp__flaggedrevs_tracking AS
SELECT  ftr_from,  ftr_namespace,  ftr_title
FROM  /*_*/flaggedrevs_tracking;
DROP  TABLE  /*_*/flaggedrevs_tracking;
CREATE TABLE  /*_*/flaggedrevs_tracking (    ftr_from INTEGER UNSIGNED DEFAULT 0 NOT NULL,    ftr_namespace INTEGER DEFAULT 0 NOT NULL,    ftr_title BLOB DEFAULT '' NOT NULL,    PRIMARY KEY(      ftr_from, ftr_namespace, ftr_title    )  );
INSERT INTO  /*_*/flaggedrevs_tracking (    ftr_from, ftr_namespace, ftr_title  )
SELECT  ftr_from,  ftr_namespace,  ftr_title
FROM  /*_*/__temp__flaggedrevs_tracking;
DROP  TABLE /*_*/__temp__flaggedrevs_tracking;
CREATE INDEX frt_namespace_title_from ON  /*_*/flaggedrevs_tracking (    ftr_namespace, ftr_title, ftr_from  );