-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: backend/schema/abstractSchemaChanges/patch-flaggedrevs_tracking-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX frt_from_namespace_title ON  /*_*/flaggedrevs_tracking;
ALTER TABLE  /*_*/flaggedrevs_tracking
ADD  PRIMARY KEY (    ftr_from, ftr_namespace, ftr_title  );